class CreateIdeaLinks < ActiveRecord::Migration
  def change
    create_table :idea_links do |t|
      t.references :idea
      t.string :title
      t.text :content
      t.string :url
      t.boolean :autogenerated
      t.timestamps
    end
  end
end
